# Generated by Django 5.1.6 on 2025-03-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_project.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_project.teacher'),
        ),
    ]
