# Generated by Django 5.1.6 on 2025-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_project', '0002_class_student_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(to='school_project.student'),
        ),
    ]
